name: 'DX Auditor'
description: 'Automated weekly DX meta-analysis to detect toil patterns'
author: 'Prime Radiant AI'

inputs:
  lookback-commits:
    description: 'Number of recent commits to analyze'
    required: false
    default: '60'
  lookback-runs:
    description: 'Number of recent CI runs to analyze'
    required: false
    default: '30'
  output-file:
    description: 'Output file path for audit report'
    required: false
    default: 'docs/DX_AUDIT_LOG.md'
  beads-epic:
    description: 'Beads epic to post summary to (e.g., bd-audit)'
    required: false
    default: ''

outputs:
  toil-rate:
    description: 'Calculated toil rate (e.g., 0.58 for 58%)'
    value: ${{ steps.analyze.outputs.toil-rate }}
  top-pattern:
    description: 'Most common toil pattern detected'
    value: ${{ steps.analyze.outputs.top-pattern }}
  report-path:
    description: 'Path to generated audit report'
    value: ${{ inputs.output-file }}

runs:
  using: 'composite'
  steps:
    - name: Collect commit data
      id: collect-commits
      shell: bash
      run: |
        echo "Collecting last ${{ inputs.lookback-commits }} commits..."

        # Get commit messages with trailers
        git log -${{ inputs.lookback-commits }} --format="%H|%s|%(trailers:key=Feature-Key,valueonly)" > /tmp/commits.txt

        TOTAL=$(wc -l < /tmp/commits.txt)
        echo "total-commits=$TOTAL" >> $GITHUB_OUTPUT
        echo "Collected $TOTAL commits"

    - name: Collect CI run data
      id: collect-ci
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        LOOKBACK_RUNS: ${{ inputs.lookback-runs }}
      run: |
        echo "Collecting last $LOOKBACK_RUNS CI runs..."

        # Get workflow run conclusions
        # Use || true to handle SIGPIPE (exit 141) when head closes pipe early
        gh api repos/${{ github.repository }}/actions/runs \
          --paginate \
          --jq '.workflow_runs[] | {id, conclusion, created_at, head_commit}' \
          2>/dev/null | head -n "$LOOKBACK_RUNS" > /tmp/ci-runs.json || true

        TOTAL=$(jq -s 'length' /tmp/ci-runs.json 2>/dev/null || echo "0")
        FAILED=$(jq -s '[.[] | select(.conclusion == "failure")] | length' /tmp/ci-runs.json 2>/dev/null || echo "0")

        echo "total-runs=$TOTAL" >> $GITHUB_OUTPUT
        echo "failed-runs=$FAILED" >> $GITHUB_OUTPUT
        echo "Collected $TOTAL runs ($FAILED failures)"


    - name: Aggregate failure patterns
      id: aggregate
      shell: bash
      run: |
        echo "Aggregating failure patterns..."

        # Create aggregation report
        {
          echo "# DX Audit Data Aggregation"
          echo ""
          echo "## Commit Analysis (${{ steps.collect-commits.outputs.total-commits }} commits)"
          echo ""
          cat /tmp/commits.txt
          echo ""
          echo "## CI Run Analysis (${{ steps.collect-ci.outputs.total-runs }} runs)"
          echo ""
          echo "- Total runs: ${{ steps.collect-ci.outputs.total-runs }}"
          echo "- Failed runs: ${{ steps.collect-ci.outputs.failed-runs }}"
          echo "- Failure rate: $(echo "scale=2; ${{ steps.collect-ci.outputs.failed-runs }} / ${{ steps.collect-ci.outputs.total-runs }} * 100" | bc)%"
          echo ""
          echo "## Common Patterns to Detect"
          echo ""
          echo "- **Lockfile drift**: Commits fixing poetry.lock or pnpm-lock.yaml drift"
          echo "- **Beads sync**: Commits fixing .beads/issues.jsonl issues"
          echo "- **Fixture config**: Commits fixing test fixture setup"
          echo "- **Python version**: Commits fixing Python version mismatches"
          echo "- **CI iterations**: Multiple commits on same feature (toil indicator)"
        } > /tmp/aggregation.md

        echo "✅ Aggregation complete"

    - name: Run Claude analysis
      id: analyze
      shell: bash
      env:
        ANTHROPIC_API_KEY: ${{ env.ANTHROPIC_API_KEY }}
        ANTHROPIC_BASE_URL: ${{ env.ANTHROPIC_BASE_URL }}
      run: |
        echo "Running Claude DX analysis..."

        # Read aggregation data
        AGGREGATION=$(cat /tmp/aggregation.md)

        # Prepare API request
        API_URL="${ANTHROPIC_BASE_URL:-https://api.anthropic.com}/v1/messages"
        MODEL="${ANTHROPIC_DEFAULT_SONNET_MODEL:-claude-sonnet-4-20250514}"

        # Create prompt with ultrathink for deep analysis
        PROMPT="You are an elite DX (Developer Experience) analyst. <ultrathink>

        Think step by step:
        1. First, categorize each commit as 'feature work' or 'toil' (work that could be automated or prevented)
        2. Identify recurring patterns in the toil commits
        3. Trace root causes and propose systemic fixes

        Here is the commit and CI data to analyze:

        ${AGGREGATION}

        Based on your deep analysis, provide:

        1. **Toil commits**: How many commits are toil vs total? Express as a fraction like '40/83 commits are toil'. Toil includes things like:
           - Fixing lockfile drift (poetry.lock, pnpm-lock.yaml)
           - Beads/JSONL sync issues
           - CI configuration fixes
           - Test fixture/config adjustments
           - Multiple commits on same PR (iteration loops)
           - Python version or dependency fixes
           - Any work that could have been prevented or automated

        2. **Top pattern**: What is the single most common toil pattern you observe? Be specific and descriptive (e.g., 'lockfile-drift', 'ci-iteration-loops', 'missing-dependency', 'test-fixture-mismatch'). These are examples - identify whatever pattern actually dominates.

        3. **Root cause**: One sentence explaining WHY this toil keeps happening.

        4. **Recommendations**: 2-3 specific, actionable improvements prioritized by impact.

        Format your response EXACTLY as:
        TOIL_FRACTION: <N>/<M> commits are toil
        TOP_PATTERN: <descriptive-pattern-name>
        ROOT_CAUSE: <one sentence>
        RECOMMENDATIONS:
        - [HIGH] <highest impact recommendation>
        - [MEDIUM] <medium impact recommendation>
        - [LOW] <lower priority recommendation>"

        # Call Claude API with timeout and error handling
        echo "Calling API at: $API_URL with model: $MODEL"
        RESPONSE=""
        CURL_EXIT=0
        RESPONSE=$(curl -s --max-time 60 -X POST "$API_URL" \
          -H "Content-Type: application/json" \
          -H "x-api-key: $ANTHROPIC_API_KEY" \
          -H "anthropic-version: 2023-06-01" \
          -d "{\"model\":\"$MODEL\",\"max_tokens\":2048,\"messages\":[{\"role\":\"user\",\"content\":$(echo "$PROMPT" | jq -Rs .)}]}" \
        ) || CURL_EXIT=$?

        if [ "$CURL_EXIT" -ne 0 ]; then
          echo "⚠️  curl failed with exit code: $CURL_EXIT"
          echo "Falling back to manual analysis..."
          TOIL_FRACTION="unknown"
          TOP_PATTERN="unknown"
          ROOT_CAUSE="LLM API unreachable"
          RECOMMENDATIONS="- Unable to reach LLM API (curl exit $CURL_EXIT)"
        else
          # Parse response
          CONTENT=$(echo "$RESPONSE" | jq -r '.content[0].text' 2>/dev/null || echo "")

          if [ -z "$CONTENT" ] || [ "$CONTENT" = "null" ]; then
            echo "⚠️  Claude API returned empty response"
            echo "Response: $RESPONSE"
            TOIL_FRACTION="unknown"
            TOP_PATTERN="unknown"
            ROOT_CAUSE="LLM returned empty"
            RECOMMENDATIONS="- LLM API returned empty response"
          else
            echo "✅ Claude analysis complete"
            echo "$CONTENT" > /tmp/claude-analysis.txt

            # Extract toil fraction (e.g., "40/83 commits are toil")
            TOIL_FRACTION=$(echo "$CONTENT" | grep -oP 'TOIL_FRACTION:\s*\K[^\n]+' | head -1 || echo "unknown")

            # Extract top pattern
            TOP_PATTERN=$(echo "$CONTENT" | grep -oP 'TOP_PATTERN:\s*\K[^\n]+' | head -1 || echo "unknown")

            # Extract root cause
            ROOT_CAUSE=$(echo "$CONTENT" | grep -oP 'ROOT_CAUSE:\s*\K[^\n]+' | head -1 || echo "unknown")

            # Extract recommendations
            RECOMMENDATIONS=$(echo "$CONTENT" | sed -n '/^RECOMMENDATIONS:/,$p' | tail -n +2 || echo "- No specific recommendations generated")
          fi
        fi

        echo "toil-fraction=$TOIL_FRACTION" >> $GITHUB_OUTPUT
        echo "top-pattern=$TOP_PATTERN" >> $GITHUB_OUTPUT
        echo "root-cause=$ROOT_CAUSE" >> $GITHUB_OUTPUT

        # Save recommendations to temp file for report generation
        echo "$RECOMMENDATIONS" > /tmp/recommendations.txt

        echo "Toil: $TOIL_FRACTION"
        echo "Top pattern: $TOP_PATTERN"
        echo "Root cause: $ROOT_CAUSE"
        echo "Recommendations extracted"

    - name: Generate audit report
      shell: bash
      run: |
        mkdir -p $(dirname ${{ inputs.output-file }})

        # Calculate failure percentage with awk
        FAILURE_PCT=$(awk "BEGIN {printf \"%.1f\", ${{ steps.collect-ci.outputs.failed-runs }} / ${{ steps.collect-ci.outputs.total-runs }} * 100}")

        # Generate report
        {
          echo "# DX Audit Report"
          echo ""
          echo "**Generated**: $(date -u +\"%Y-%m-%d %H:%M:%S UTC\")"
          echo "**Commits analyzed**: ${{ steps.collect-commits.outputs.total-commits }}"
          echo "**CI runs analyzed**: ${{ steps.collect-ci.outputs.total-runs }}"
          echo ""
          echo "## Summary"
          echo ""
          echo "- **Toil**: ${{ steps.analyze.outputs.toil-fraction }}"
          echo "- **Top pattern**: ${{ steps.analyze.outputs.top-pattern }}"
          echo "- **Root cause**: ${{ steps.analyze.outputs.root-cause }}"
          echo "- **CI failure rate**: ${FAILURE_PCT}%"
          echo ""
          echo "## Recommendations"
          echo ""
          cat /tmp/recommendations.txt 2>/dev/null || echo "- No recommendations available"
          echo ""
          echo "## Data"
          echo ""
          echo "See /tmp/aggregation.md for full analysis data."
        } > ${{ inputs.output-file }}

        echo "✅ Report generated: ${{ inputs.output-file }}"

    - name: Create GitHub Issue for tracking
      id: create-issue
      if: inputs.beads-epic != ''
      shell: bash
      run: |
        WEEK=$(date +%Y-W%W)
        TOIL="${{ steps.analyze.outputs.toil-fraction }}"
        PATTERN="${{ steps.analyze.outputs.top-pattern }}"
        
        # Build body with report + metadata
        BODY=$(cat ${{ inputs.output-file }})
        BODY="${BODY}

        ___
        **Parent Epic**: ${{ inputs.beads-epic }}
        **Generated by**: dx-audit workflow"
        
        # Create issue with structured title for easy querying
        ISSUE_URL=$(gh issue create \
          --title "DX Audit ${WEEK}: ${TOIL}, ${PATTERN}" \
          --body "$BODY" \
          --label "dx-audit,automated" 2>&1) || {
          echo "⚠️  Failed to create GitHub Issue (may lack permissions)"
          echo "issue-created=false" >> $GITHUB_OUTPUT
          exit 0
        }
        
        echo "✅ Created GitHub Issue: $ISSUE_URL"
        echo "issue-url=$ISSUE_URL" >> $GITHUB_OUTPUT
        echo "issue-created=true" >> $GITHUB_OUTPUT

    - name: Sync to Beads (best-effort)
      id: beads-sync
      if: inputs.beads-epic != '' && steps.create-issue.outputs.issue-created == 'true'
      continue-on-error: true
      shell: bash
      run: |
        # This step is best-effort - if it fails, GH Issue is still the record
        if ! command -v bd &> /dev/null; then
          echo "⚠️  bd CLI not available"
          echo "sync-status=no-cli" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        if [ ! -d .beads ]; then
          echo "⚠️  No .beads directory in workspace"
          echo "sync-status=no-db" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        WEEK=$(date +%Y-W%W)
        TOIL="${{ steps.analyze.outputs.toil-fraction }}"
        PATTERN="${{ steps.analyze.outputs.top-pattern }}"
        ISSUE_URL="${{ steps.create-issue.outputs.issue-url }}"
        
        # Build description (single line to avoid YAML issues)
        DESC="DX Audit. GitHub Issue: ${ISSUE_URL} | Toil: ${TOIL} | Pattern: ${PATTERN}"
        
        # Create child issue under epic using --no-db to avoid SQLite requirement
        bd --no-db create "DX Audit ${WEEK}: ${TOIL}, ${PATTERN}" \
          --type task \
          --parent ${{ inputs.beads-epic }} \
          --description "$DESC" || {
          echo "⚠️  bd create failed"
          echo "sync-status=failed" >> $GITHUB_OUTPUT
          exit 1  # This will be caught by continue-on-error
        }
        
        echo "✅ Created Beads issue under ${{ inputs.beads-epic }}"
        echo "sync-status=created" >> $GITHUB_OUTPUT

    - name: Commit Beads JSONL
      id: commit-beads
      if: steps.beads-sync.outputs.sync-status == 'created'
      continue-on-error: true
      shell: bash
      run: |
        # Check if there are changes to commit
        if [ -z "$(git status --porcelain .beads/issues.jsonl 2>/dev/null)" ]; then
          echo "No changes to .beads/issues.jsonl"
          echo "commit-status=no-changes" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        # Configure git for commit
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        # Commit and push
        git add .beads/issues.jsonl
        COMMIT_MSG="chore: sync DX audit to Beads [skip ci]"
        git commit -m "$COMMIT_MSG" -m "Feature-Key: ${{ inputs.beads-epic }}" -m "Agent: dx-auditor"
        
        git push || {
          echo "⚠️  git push failed (may need contents:write permission)"
          echo "commit-status=push-failed" >> $GITHUB_OUTPUT
          exit 1
        }
        
        echo "✅ Committed Beads JSONL"
        echo "commit-status=ok" >> $GITHUB_OUTPUT

    - name: Summary
      shell: bash
      run: |
        echo "### DX Audit Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "- **Toil**: ${{ steps.analyze.outputs.toil-fraction }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Top pattern**: ${{ steps.analyze.outputs.top-pattern }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Root cause**: ${{ steps.analyze.outputs.root-cause }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        # Show tracking status
        if [ "${{ steps.create-issue.outputs.issue-created }}" = "true" ]; then
          echo "- **Tracking**: [GitHub Issue](${{ steps.create-issue.outputs.issue-url }})" >> $GITHUB_STEP_SUMMARY
        fi
        
        # Beads sync status
        SYNC="${{ steps.beads-sync.outputs.sync-status }}"
        COMMIT="${{ steps.commit-beads.outputs.commit-status }}"
        
        if [ "$SYNC" = "created" ] && [ "$COMMIT" = "ok" ]; then
          echo "- **Beads**: ✅ Synced and committed to ${{ inputs.beads-epic }}" >> $GITHUB_STEP_SUMMARY
        elif [ "$SYNC" = "created" ] && [ "$COMMIT" = "push-failed" ]; then
          echo "- **Beads**: ⚠️ Created but push failed (check permissions)" >> $GITHUB_STEP_SUMMARY
        elif [ "$SYNC" = "created" ]; then
          echo "- **Beads**: ⚠️ Created but not committed" >> $GITHUB_STEP_SUMMARY
        elif [ "$SYNC" = "no-cli" ] || [ "$SYNC" = "no-db" ]; then
          echo "- **Beads**: ⏭️ Skipped (bd CLI or .beads not available)" >> $GITHUB_STEP_SUMMARY
        elif [ "$SYNC" = "failed" ]; then
          echo "- **Beads**: ❌ Sync failed (see logs)" >> $GITHUB_STEP_SUMMARY
        fi
        
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "- **Report**: [${{ inputs.output-file }}](${{ inputs.output-file }})" >> $GITHUB_STEP_SUMMARY
