#!/usr/bin/env bash
# worktree-setup.sh <beads-id> <repo-name>
# Creates an isolated git worktree for a specific agent task.
#
# Usage:
#   ./worktree-setup.sh bd-123 prime-radiant-ai

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

BEADS_ID="${1:-}"
REPO_NAME="${2:-}"

if [[ -z "$BEADS_ID" || -z "$REPO_NAME" ]]; then
    echo "Usage: $0 <beads-id> <repo-name>" >&2
    exit 1
fi

# Base directory for all agent worktrees
WORKTREE_BASE="/tmp/agents"
TARGET_DIR="$WORKTREE_BASE/$BEADS_ID/$REPO_NAME"
REPO_PATH="$HOME/$REPO_NAME"

start_semantic_prewarm() {
    local worktree_dir="$1"
    local prewarm_script="$SCRIPT_DIR/tldr-semantic-prewarm.sh"
    local log_file="$HOME/logs/dx/tldr-semantic-prewarm-worktree.log"

    [[ -x "$prewarm_script" ]] || return 0
    mkdir -p "$HOME/logs/dx" >/dev/null 2>&1 || true
    nohup "$prewarm_script" --path "$worktree_dir" >>"$log_file" 2>&1 &
}

seed_railway_context() {
    local canonical_repo="$1"
    local worktree_dir="$2"
    local repo_name="$3"
    local status_text status_json project_id env_name service_name
    local context_base context_file context_dir tmp_context_file

    command -v railway >/dev/null 2>&1 || return 0

    status_text="$(cd "$canonical_repo" && railway status 2>/dev/null || true)"
    [[ -n "$status_text" ]] || return 0

    status_json="$(cd "$canonical_repo" && railway status --json 2>/dev/null || true)"
    project_id="$(
        printf '%s' "$status_json" | python3 -c '
import json
import sys
try:
    data = json.load(sys.stdin)
except Exception:
    print("")
    raise SystemExit(0)
print(data.get("id", ""))
' 2>/dev/null || true
    )"
    [[ -n "$project_id" ]] || {
        echo "worktree-setup: warning: unable to resolve Railway project id from $canonical_repo" >&2
        return 0
    }

    env_name="$(printf '%s\n' "$status_text" | awk -F': ' '/^Environment:/ {print $2; exit}')"
    service_name="$(printf '%s\n' "$status_text" | awk -F': ' '/^Service:/ {print $2; exit}')"

    env_name="${env_name:-dev}"
    if [[ -z "$service_name" ]]; then
        case "$repo_name" in
            prime-radiant-ai|affordabot)
                service_name="backend"
                ;;
            *)
                service_name=""
                ;;
        esac
    fi

    # Store generated Railway context outside repo trees to avoid git diff noise.
    context_base="${DX_WORKTREE_CONTEXT_BASE:-$WORKTREE_BASE/.dx-context}"
    context_dir="$context_base/$BEADS_ID/$repo_name"
    context_file="$context_dir/railway-context.env"
    mkdir -p "$context_dir"
    tmp_context_file="$(mktemp "$context_dir/.railway-context.XXXXXX.tmp" 2>/dev/null || true)"
    if [[ -z "$tmp_context_file" ]]; then
        tmp_context_file="$context_file.tmp.$$"
    fi

    cat > "$tmp_context_file" <<EOF
# Auto-generated by worktree-setup.sh
RAILWAY_PROJECT_ID=$project_id
RAILWAY_ENVIRONMENT=$env_name
RAILWAY_SERVICE=$service_name
RAILWAY_CONTEXT_SOURCE=$canonical_repo
RAILWAY_CONTEXT_CAPTURED_AT=$(date -u +%Y-%m-%dT%H:%M:%SZ)
EOF
    chmod 600 "$tmp_context_file" 2>/dev/null || true
    mv "$tmp_context_file" "$context_file"

    (
        cd "$worktree_dir"
        if [[ -n "$service_name" ]]; then
            railway link -p "$project_id" -e "$env_name" -s "$service_name" >/dev/null 2>&1 \
                || railway link -p "$project_id" -e "$env_name" >/dev/null 2>&1 \
                || railway link -p "$project_id" >/dev/null 2>&1 \
                || true
        else
            railway link -p "$project_id" -e "$env_name" >/dev/null 2>&1 \
                || railway link -p "$project_id" >/dev/null 2>&1 \
                || true
        fi
    )
}

# Verify repo exists
if [[ ! -d "$REPO_PATH/.git" ]]; then
    echo "Error: Repository $REPO_PATH not found or not a git repo" >&2
    exit 1
fi

# Create base dir if needed
mkdir -p "$WORKTREE_BASE/$BEADS_ID"

# Navigate to main repo
cd "$REPO_PATH"

# V8.1: Ensure hooks are enforced via core.hooksPath for canonical repos.
# This must run before creating the worktree so the common-dir hook state is correct.
CANONICAL_REPOS=(agent-skills prime-radiant-ai affordabot llm-common)
is_canonical_repo=0
for r in "${CANONICAL_REPOS[@]}"; do
    if [[ "$REPO_NAME" == "$r" ]]; then
        is_canonical_repo=1
        break
    fi
done

if [[ "$is_canonical_repo" == "1" ]]; then
    if [[ ! -d "$REPO_PATH/.githooks" ]]; then
        echo "Error: $REPO_PATH is missing .githooks/ (required for DX V8.1 guardrails)" >&2
        exit 1
    fi
    git config core.hooksPath .githooks 2>/dev/null || true
    if [[ -x "$REPO_PATH/.githooks/_bootstrap.sh" ]]; then
        "$REPO_PATH/.githooks/_bootstrap.sh" >/dev/null 2>&1 || true
    fi
fi

# Determine origin default branch (origin/HEAD).
# Fleet standard is "master", but some repos may use "main".
DEFAULT_BRANCH="$(
    git symbolic-ref --quiet --short refs/remotes/origin/HEAD 2>/dev/null | sed 's@^origin/@@' || true
)"
DEFAULT_BRANCH="${DEFAULT_BRANCH:-master}"
UPSTREAM_REF="origin/${DEFAULT_BRANCH}"

# Fetch latest default branch
git fetch --quiet --prune origin "${DEFAULT_BRANCH}" || git fetch --quiet --prune origin || true

# Create worktree
# Strategy:
# 1. Try creating new branch 'feature-$BEADS_ID'
# 2. If branch exists, checkout existing branch
# 3. If worktree dir exists, ensure it's clean/locked? (For now assuming new dir)

if [[ -d "$TARGET_DIR" ]]; then
    echo "Worktree directory $TARGET_DIR already exists" >&2
    seed_railway_context "$REPO_PATH" "$TARGET_DIR" "$REPO_NAME" || true
    start_semantic_prewarm "$TARGET_DIR" || true
    if [[ -x "$SCRIPT_DIR/dx-session-lock.sh" ]]; then
        "$SCRIPT_DIR/dx-session-lock.sh" touch "$TARGET_DIR" >/dev/null 2>&1 || true
    fi
    echo "$TARGET_DIR"
    exit 0
fi

BRANCH="feature-$BEADS_ID"

# Try creating worktree with new branch
if git worktree add "$TARGET_DIR" -b "$BRANCH" "$UPSTREAM_REF" > /dev/null 2>&1; then
    seed_railway_context "$REPO_PATH" "$TARGET_DIR" "$REPO_NAME" || true
    start_semantic_prewarm "$TARGET_DIR" || true
    if [[ -x "$SCRIPT_DIR/dx-session-lock.sh" ]]; then
        "$SCRIPT_DIR/dx-session-lock.sh" touch "$TARGET_DIR" >/dev/null 2>&1 || true
    fi
    echo "$TARGET_DIR"
    exit 0
fi

# Fallback: Branch might already exist, try checking it out
if git worktree add "$TARGET_DIR" "$BRANCH" > /dev/null 2>&1; then
    seed_railway_context "$REPO_PATH" "$TARGET_DIR" "$REPO_NAME" || true
    start_semantic_prewarm "$TARGET_DIR" || true
    if [[ -x "$SCRIPT_DIR/dx-session-lock.sh" ]]; then
        "$SCRIPT_DIR/dx-session-lock.sh" touch "$TARGET_DIR" >/dev/null 2>&1 || true
    fi
    echo "$TARGET_DIR"
    exit 0
fi

echo "Error: Failed to create worktree at $TARGET_DIR" >&2
exit 1
