name: 'Lockfile Guardian'
description: 'Ensures lockfiles are in sync with manifest changes'
inputs:
  github-token:
    description: 'GitHub Token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Check Python Lockfile
      shell: bash
      run: |
        if git diff --name-only origin/${{ github.base_ref }}..HEAD | grep -q 'pyproject.toml'; then
          if ! git diff --name-only origin/${{ github.base_ref }}..HEAD | grep -q 'poetry.lock'; then
            echo "::error::pyproject.toml changed but poetry.lock did not. Run 'poetry lock' locally."
            exit 1
          fi
        fi

    - name: Check JS Lockfile
      shell: bash
      run: |
        if git diff --name-only origin/${{ github.base_ref }}..HEAD | grep -q 'package.json'; then
          if ! git diff --name-only origin/${{ github.base_ref }}..HEAD | grep -q 'pnpm-lock.yaml'; then
            echo "::error::package.json changed but pnpm-lock.yaml did not. Run 'pnpm install' locally."
            exit 1
          fi
        fi